package com.cloudcog.gears.screen.admin.users;

import com.cloudcog.gears.controller.admin.AdminScreenController;
import com.cloudcog.gears.controller.users.UserHelper;
import com.cloudcog.gears.repository.user.GearsUser;
import com.cloudcog.gears.screen.GearsWindow;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.Resource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class UsersPanel extends GearsWindow {
	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private TabSheet detailsTab;

	@AutoGenerated
	private Panel groupsPanel;

	@AutoGenerated
	private VerticalLayout verticalLayout_2;

	@AutoGenerated
	private Panel additionalAttributes;

	@AutoGenerated
	private VerticalLayout attributesLayout;

	@AutoGenerated
	private Table propertiesTable;

	@AutoGenerated
	private TextArea userAddressTxt;

	@AutoGenerated
	private CheckBox genderMale;

	@AutoGenerated
	private TextField userEmailTxt;

	@AutoGenerated
	private TextField userLastNameTxt;

	@AutoGenerated
	private TextField userFirstNameTxt;

	@AutoGenerated
	private TextField usernameTxt;

	private GearsUser user;

	private static final long serialVersionUID = 4560102818476134442L;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */

	@Override
	public void initialize(AdminScreenController adminScreenController, Object item) {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		this.setSizeFull();

		this.setData(item);
		try {
			this.user = (GearsUser) item;
			usernameTxt.setValue(user.getUsername());
			userFirstNameTxt.setValue(user.getFirstName());
			userLastNameTxt.setValue(user.getLastName());
			userAddressTxt.setValue(user.getAddress());

		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	@Override
	public String getCaption() {
		return user.toString();
	}

	@Override
	public Resource getIcon() {
		try {
			return UserHelper.getUserIcon(this.user);
		} catch (Exception e) {
			return super.getIcon();
		}
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// usernameTxt
		usernameTxt = new TextField();
		usernameTxt.setStyleName("small");
		usernameTxt.setCaption("Username");
		usernameTxt.setImmediate(false);
		usernameTxt.setWidth("-1px");
		usernameTxt.setHeight("-1px");
		mainLayout.addComponent(usernameTxt);

		// userFirstNameTxt
		userFirstNameTxt = new TextField();
		userFirstNameTxt.setStyleName("small");
		userFirstNameTxt.setCaption("First Name");
		userFirstNameTxt.setImmediate(false);
		userFirstNameTxt.setWidth("-1px");
		userFirstNameTxt.setHeight("-1px");
		mainLayout.addComponent(userFirstNameTxt);

		// userLastNameTxt
		userLastNameTxt = new TextField();
		userLastNameTxt.setStyleName("small");
		userLastNameTxt.setCaption("Last Name");
		userLastNameTxt.setImmediate(false);
		userLastNameTxt.setWidth("-1px");
		userLastNameTxt.setHeight("-1px");
		mainLayout.addComponent(userLastNameTxt);

		// userEmailTxt
		userEmailTxt = new TextField();
		userEmailTxt.setCaption("Email");
		userEmailTxt.setImmediate(false);
		userEmailTxt.setStyleName("small");
		userEmailTxt.setWidth("-1px");
		userEmailTxt.setHeight("-1px");
		mainLayout.addComponent(userEmailTxt);

		// genderMale
		genderMale = new CheckBox();
		genderMale.setStyleName("small");
		genderMale.setCaption("Gender");
		genderMale.setImmediate(false);
		genderMale.setWidth("-1px");
		genderMale.setHeight("-1px");
		mainLayout.addComponent(genderMale);

		// userAddressTxt
		userAddressTxt = new TextArea();
		userAddressTxt.setStyleName("small");
		userAddressTxt.setCaption("Address");
		userAddressTxt.setImmediate(false);
		userAddressTxt.setWidth("300px");
		userAddressTxt.setHeight("100px");
		mainLayout.addComponent(userAddressTxt);

		// detailsTab
		detailsTab = buildDetailsTab();
		mainLayout.addComponent(detailsTab);
		mainLayout.setComponentAlignment(detailsTab, new Alignment(33));

		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildDetailsTab() {
		// common part: create layout
		detailsTab = new TabSheet();
		detailsTab.setImmediate(true);
		detailsTab.setWidth("100.0%");
		detailsTab.setHeight("100.0%");

		// additionalAttributes
		additionalAttributes = buildAdditionalAttributes();
		detailsTab.addTab(additionalAttributes, "Additional Attributes", null);

		// groupsPanel
		groupsPanel = buildGroupsPanel();
		detailsTab.addTab(groupsPanel, "Groups", null);

		return detailsTab;
	}

	@AutoGenerated
	private Panel buildAdditionalAttributes() {
		// common part: create layout
		additionalAttributes = new Panel();
		additionalAttributes.setCaption("Additional Attributes");
		additionalAttributes.setImmediate(false);
		additionalAttributes.setWidth("100px");
		additionalAttributes.setHeight("30px");

		// attributesLayout
		attributesLayout = buildAttributesLayout();
		additionalAttributes.setContent(attributesLayout);

		return additionalAttributes;
	}

	@AutoGenerated
	private VerticalLayout buildAttributesLayout() {
		// common part: create layout
		attributesLayout = new VerticalLayout();
		attributesLayout.setImmediate(false);
		attributesLayout.setWidth("100.0%");
		attributesLayout.setHeight("100.0%");
		attributesLayout.setMargin(false);

		// propertiesTable
		propertiesTable = new Table();
		propertiesTable.setImmediate(false);
		propertiesTable.setWidth("100.0%");
		propertiesTable.setHeight("100.0%");
		attributesLayout.addComponent(propertiesTable);

		return attributesLayout;
	}

	@AutoGenerated
	private Panel buildGroupsPanel() {
		// common part: create layout
		groupsPanel = new Panel();
		groupsPanel.setCaption("Groups");
		groupsPanel.setImmediate(false);
		groupsPanel.setWidth("100px");
		groupsPanel.setHeight("30px");

		// verticalLayout_2
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setMargin(false);
		groupsPanel.setContent(verticalLayout_2);

		return groupsPanel;
	}

}
