package com.cloudcog.gears.screen.admin.groups;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.cloudcog.gears.GearsContext;
import com.cloudcog.gears.controller.admin.AdminScreenController;
import com.cloudcog.gears.i18n.Messages;
import com.cloudcog.gears.repository.user.GearsGroup;
import com.cloudcog.gears.repository.user.UserDAO;
import com.cloudcog.gears.screen.GearsWindow;
import com.cloudcog.gears.screen.mainPanel.ObjectMenuBar;
import com.cloudcog.gears.screen.mainPanel.handlers.SaveObjectInterface;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class GroupsPanel extends GearsWindow implements SaveObjectInterface {
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final Logger log = LoggerFactory.getLogger(GroupsPanel.class);

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private TextField groupNameText;

	private static final long serialVersionUID = 2096197583396700915L;

	GearsGroup gearsGroup;

	@Override
	public void initialize(AdminScreenController adminScreenController, Object item) {
		buildMainLayout();
		this.gearsGroup = (GearsGroup) item;
		setCompositionRoot(mainLayout);

	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();

		mainLayout.addComponent(new ObjectMenuBar(this));

		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%"); //$NON-NLS-1$
		mainLayout.setHeight("100%"); //$NON-NLS-1$
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("100.0%"); //$NON-NLS-1$
		setHeight("100.0%"); //$NON-NLS-1$

		// groupNameText
		groupNameText = new TextField();
		groupNameText.setCaption(Messages.getString("GroupsPanel.GroupName")); //$NON-NLS-1$
		groupNameText.setImmediate(false);
		groupNameText.setDescription(Messages.getString("GroupsPanel.GroupNameDesc")); //$NON-NLS-1$
		groupNameText.setWidth("-1px"); //$NON-NLS-1$
		groupNameText.setHeight("-1px"); //$NON-NLS-1$
		mainLayout.addComponent(groupNameText);

		return mainLayout;
	}

	@Override
	public void save() {
		try {
			if (this.getData() == null) {

				this.gearsGroup = new GearsGroup(UserDAO.createGroup(GearsContext.getJcrSession(), groupNameText.getValue()));
			}
			GearsContext.getJcrSession().save();

		} catch (Exception e) {
			log.error(e.getMessage(), e);
		}

	}

}
