package com.cloudcog.gears.screen.admin.groups;

import com.cloudcog.gears.controller.admin.AdminScreenController;
import com.cloudcog.gears.i18n.Messages;
import com.cloudcog.gears.screen.GearsWindow;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class GroupsPanel extends GearsWindow {
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private TextField groupNameText;

	private static final long serialVersionUID = 2096197583396700915L;

	@Override
	public void initialize(AdminScreenController adminScreenController, Object item) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%"); //$NON-NLS-1$
		mainLayout.setHeight("100%"); //$NON-NLS-1$
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("100.0%"); //$NON-NLS-1$
		setHeight("100.0%"); //$NON-NLS-1$

		// groupNameText
		groupNameText = new TextField();
		groupNameText.setCaption(Messages.getString("GroupsPanel.GroupName")); //$NON-NLS-1$
		groupNameText.setImmediate(false);
		groupNameText.setDescription(Messages.getString("GroupsPanel.GroupNameDesc")); //$NON-NLS-1$
		groupNameText.setWidth("-1px"); //$NON-NLS-1$
		groupNameText.setHeight("-1px"); //$NON-NLS-1$
		mainLayout.addComponent(groupNameText);

		return mainLayout;
	}

}
